### ISSUE TITLE
Force drawer open in landscape orientation

### ISSUE THREAD

**Issue by russellquinn** [mutualmobile/MMDrawerController#111]
I have a left drawer, which I want to force open in iPad landscape orientation (mirroring UISplitViewController behavior).

Obviously I can programmatically open, and then remove all gestures and buttons, but the center view needs to be resized too, etc.

Any tips on the best way of doing this within MMDrawerController?

Thanks,

Russell.

**Comment by nfranke** [comment]
I have a mostly iPhone interface so I wanted to keep the left menu open all the time (landscape and portrait.) I found it pretty easy to just create a view with two subviews. I put my menu in the left one (that has a fixed width of 240 pixels), then tell MMDrawerController it only has a right menu.

 When changing the center view, make sure you turn off animations for the ``setCenterViewController:withFullCloseAnimation:completion`` or the view goes crazy. Otherwise, everything seems to work just fine, including rotation.

If you wanted to just do this for landscape, you may be able to do something similar and move the menu view controller on rotation to landscape and turn on the left menu in your MMDrawerController, i.e. don't rely on MMDrawerController to do any of this.
