### ISSUE TITLE
Bug on MMDrawerController framework 

### ISSUE THREAD

**Issue by hoangthanhdoan** [mutualmobile/MMDrawerController#204]
Hi developer of MMDrawerController

I found some bugs on your MMDrawerController framework.
I tested on your example. (download at https://github.com/mutualmobile/MMDrawerController)

Please see evidences:
![img_1599](https://f.cloud.github.com/assets/6348193/1937404/a46e05ce-7f23-11e3-830f-470cac385ef1.PNG)
![img_1619](https://f.cloud.github.com/assets/6348193/1937405/a4731b18-7f23-11e3-9d26-ff6bc54eb18a.PNG)
![img_1600](https://f.cloud.github.com/assets/6348193/1937406/a47344ee-7f23-11e3-85c4-30286f3a9698.PNG)
![img_1618](https://f.cloud.github.com/assets/6348193/1937407/a47394a8-7f23-11e3-827e-f31f5547b642.PNG)

This is the steps to reproduce:
Test case 1 : Swiping centerController left and right quickly for open/close slide menu
Test case 2 : Rotating screen while opening left menu

Please answer me: How to resolve this issue? Please let me know if you have any solution for this problem.

You can contact me for more detail.

**Comment by altagir** [comment]
still present in 0.6.0
open left view, drag... rotate while holding,... left view is black.... 
have to kill app after that

issue actually arise because of setting setMaximumLeftDrawerWidth while doing rotations...
since i always need the left drawer to be full width.... is there any toher way to fix that ?
