### ISSUE TITLE
Center/Right/Left memory leak

### ISSUE THREAD

**Issue by danielgomezrico** [mutualmobile/MMDrawerController#325]
Hi

I have an app that have a tab bar and inside of a view I have this drawer.
I just saw that the references of left/right/center view controllers are strong and they are never released.

Is this a bug?

**Comment by grabbou** [comment]
Nope, it's not. That's totally normal, usually in iOS development, parent view/controller keeps strong references to its childs. That's why when you create your interface with IB and load XIB file, IB assigns them as @property (nonatomic, weak) IBOutlet... as they are already kept strong by their `parents`

**Comment by danielgomezrico** [comment]
You are right. It's fine, excuse me.
