### ISSUE TITLE
keyboard doesn't move with center view

### ISSUE THREAD

**Issue by ghazel** [mutualmobile/MMDrawerController#335]
When opening the drawer, the keyboard is dismissed. (Sometimes it comes back when the draw is closed, but not always?).

Native iOS push and pop transitions carry the keyboard along with the viewController it is visible on. In Messages, for example, when typing a reply: tap Details. Notice the keyboard shifts along with the messages view, and when you go Back, it's there waiting. This is the behavior I would expect from MMDrawerController's center view.

Instead, what happens is the keyboard stays centered, while the input bar and center view slide off to the side. Very weird.

**Comment by kcharwood** [comment]
Hey ghazel.

I'm not aware of a way where we could partially slide the keyboard but not all the way out since the center view isn't being dismissed from the screen.

The scenario you are describing with UINavigationController I think has some special sauce in it that we don't have in the public API.

This would probably be better managed by tracking the first responder, and re-presenting the keyboard when your center view is back showing by itself.
